#! /usr/bin/env python3
# Using /home/teuben/LMT/lmtoy/data_lmt/unity/data_lmt.log
# 2021-S1-US-19 - Science
#   script generated by source_obsnum.sh
import os
import sys

from lmtoy import runs

project="2021-S1-US-19"

# Dictionary of sources, each with a list of obsnum's in this project
# negative obsnums are ignored in the combinations. See also comments.txt
# for obsnum specific comments and parameters!
on = {}

on["Cyg_X-1"] = \
 [ 98626, 98627, 98628, 98630, 98631, 98632, 100337, 100338, 100339, 100341, 100342, 100343, 100345, 100346, 100347, 100350, 100351, 100352, 100354, 100355, 100356, 100445, 100446, 100447, 100449, 100450, 100451, 100453, 100454, 100455, 100458, 100459, 100460, 100462, 100463, 100464, 100466, 100467, 100468, 100471, 100472, 100473,]

# parameters for the first pass of the pipeline (restart=1 is automatically enforced here)
pars1 = {}

pars1["Cyg_X-1"] = ""

# parameters for the (optional) second pass of the pipeline (e.g. for bank=0)
pars2 = {}

pars2["Cyg_X-1"] = ""

# parameters for the (optional) third pass of the pipeline (usually for bank=1)
pars3 = {}

pars3["Cyg_X-1"] = ""

# Found 1 source(s) for 2021-S1-US-19

if __name__ == "__main__":
    runs.mk_runs(project, on, pars1, pars2, pars3, sys.argv)
